#pragma once

enum ErrorCode_t
{
   STATUS_SUCCESS,
   ERR_TRANSPORT_SOCKET_CREATION_FAILED,
   ERR_TRANSPORT_BIND_FAILED,
   ERR_TRANSPORT_LISTEN_FAILED,
   ERR_TRANSPORT_FAIL_TO_XMIT_ALL_DATA,
   ERR_TRANSPORT_CONNECTION_CLOSED,
};
